export type ButtonActions =
  | 'Undo'
  | 'Redo'
  | 'Text'
  | 'H1'
  | 'H2'
  | 'H3'
  | 'H4'
  | 'H5'
  | 'H6'
  | 'NumberList'
  | 'BulletList'
  | 'CheckList'
  | 'Quote'
  | 'CodeBlock'
  | 'Bold'
  | 'Italic'
  | 'Underline'
  | 'Code'
  | 'Link'
  | 'FontSize'
  | 'Lowercase'
  | 'Uppercase'
  | 'Capitalize'
  | 'Strikethrough'
  | 'Subscript'
  | 'Superscript'
  | 'Highlight'
  | 'Clear'
  | 'Horizontal'
  | 'PageBreak'
  | 'Table'
  | 'Image'
  | 'Columns'
  | 'Collapsible'
  | 'Video'
  | 'LeftAlign'
  | 'CenterAlign'
  | 'RightAlign'
  | 'Indent'
  | 'Outdent'

export type DropdownActions =
  | 'TextColor'
  | 'TextBackgroundColor'
  | 'FontFamily'

export type ToolbarActions = (ButtonActions | DropdownActions | ButtonActions[])[]
